"""add folders categories user_categories documents

Revision ID: 00a0696a67f2
Revises: 2e8a9586db58
Create Date: 2026-05-11 22:14:38.984925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a0696a67f2'
down_revision: Union[str, Sequence[str], None] = '2e8a9586db58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_owner_id', 'categories', ['owner_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folders_owner_id', 'folders', ['owner_id'], unique=False)
    op.create_index('ix_folders_parent_id', 'folders', ['parent_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_documents_category_id', 'documents', ['category_id'], unique=False)
    op.create_index('ix_documents_folder_id', 'documents', ['folder_id'], unique=False)
    op.create_index('ix_documents_is_deleted', 'documents', ['is_deleted'], unique=False)
    op.create_index('ix_documents_owner_deleted', 'documents', ['owner_id', 'is_deleted'], unique=False)
    op.create_index('ix_documents_owner_id', 'documents', ['owner_id'], unique=False)
    op.create_table('user_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_index('ix_user_categories_category_id', 'user_categories', ['category_id'], unique=False)
    op.create_index('ix_user_categories_user_id', 'user_categories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_categories_user_id', table_name='user_categories')
    op.drop_index('ix_user_categories_category_id', table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index('ix_documents_owner_id', table_name='documents')
    op.drop_index('ix_documents_owner_deleted', table_name='documents')
    op.drop_index('ix_documents_is_deleted', table_name='documents')
    op.drop_index('ix_documents_folder_id', table_name='documents')
    op.drop_index('ix_documents_category_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_folders_parent_id', table_name='folders')
    op.drop_index('ix_folders_owner_id', table_name='folders')
    op.drop_table('folders')
    op.drop_index('ix_categories_owner_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
