"""update_audit_logs

Revision ID: 16f8bbef3540
Revises: 4a4946fedef9
Create Date: 2026-05-13 21:46:07.173652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f8bbef3540'
down_revision: Union[str, Sequence[str], None] = '4a4946fedef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'category_id')
    op.drop_column('audit_logs', 'folder_id')
    # ### end Alembic commands ###
