"""add unique constraint category owner name

Revision ID: 4a32a62bad70
Revises: 9a9754b8ac44
Create Date: 2026-05-16 16:48:55.637065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a32a62bad70'
down_revision: Union[str, Sequence[str], None] = '9a9754b8ac44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_owner_name', 'categories', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_owner_name', 'categories', type_='unique')
    # ### end Alembic commands ###
