"""add unique constraint folder owner parent name

Revision ID: 9a9754b8ac44
Revises: 7a33211e6f88
Create Date: 2026-05-16 16:46:11.331535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9754b8ac44'
down_revision: Union[str, Sequence[str], None] = '7a33211e6f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_folder_owner_parent_name', 'folders', ['owner_id', 'parent_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_folder_owner_parent_name', 'folders', type_='unique')
    # ### end Alembic commands ###
